/* 
 * BlackFox
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = BlackFoxCSharp.Client.OpenAPIDateConverter;

namespace BlackFoxCSharp.Model
{
    /// <summary>
    /// Defines AggregationType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum AggregationType
    {
        /// <summary>
        /// Enum Avg for value: Avg
        /// </summary>
        [EnumMember(Value = "Avg")]
        Avg = 1,

        /// <summary>
        /// Enum Sum for value: Sum
        /// </summary>
        [EnumMember(Value = "Sum")]
        Sum = 2,

        /// <summary>
        /// Enum None for value: None
        /// </summary>
        [EnumMember(Value = "None")]
        None = 3

    }

}
