/* 
 * BlackFox
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = BlackFoxCSharp.Client.OpenAPIDateConverter;

namespace BlackFoxCSharp.Model
{
    /// <summary>
    /// Defines NeuralNetworkType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum NeuralNetworkType
    {
        /// <summary>
        /// Enum H5 for value: h5
        /// </summary>
        [EnumMember(Value = "h5")]
        H5 = 1,

        /// <summary>
        /// Enum Onnx for value: onnx
        /// </summary>
        [EnumMember(Value = "onnx")]
        Onnx = 2,

        /// <summary>
        /// Enum Pb for value: pb
        /// </summary>
        [EnumMember(Value = "pb")]
        Pb = 3

    }

}
