/* 
 * BlackFox
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = BlackFoxCSharp.Client.OpenAPIDateConverter;

namespace BlackFoxCSharp.Model
{
    /// <summary>
    /// OptimizationEngineConfig
    /// </summary>
    [DataContract]
    public partial class OptimizationEngineConfig :  IEquatable<OptimizationEngineConfig>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OptimizationEngineConfig" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OptimizationEngineConfig() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OptimizationEngineConfig" /> class.
        /// </summary>
        /// <param name="crossoverDistributionIndex">crossoverDistributionIndex (default to 20).</param>
        /// <param name="crossoverProbability">crossoverProbability (default to 0.9D).</param>
        /// <param name="mutationDistributionIndex">mutationDistributionIndex (default to 20).</param>
        /// <param name="mutationProbability">mutationProbability.</param>
        /// <param name="procTimeoutSeconds">Time in seconds in which individual network must finish training.  If not finished in time error will have maximum value. (required) (default to 10800).</param>
        /// <param name="maxNumOfGenerations">Maximum number of generations in which to find optimal network (required) (default to 50).</param>
        /// <param name="populationSize">Number of individials in one generation (default to 50).</param>
        /// <param name="hyperVolume">Define hyper volume for early stopping.</param>
        public OptimizationEngineConfig(int crossoverDistributionIndex = 20, double crossoverProbability = 0.9D, int mutationDistributionIndex = 20, double mutationProbability = default(double), int procTimeoutSeconds = 10800, int maxNumOfGenerations = 50, int populationSize = 50, ConvergencyCriterion hyperVolume = default(ConvergencyCriterion))
        {
            // to ensure "procTimeoutSeconds" is required (not null)
            if (procTimeoutSeconds == null)
            {
                throw new InvalidDataException("procTimeoutSeconds is a required property for OptimizationEngineConfig and cannot be null");
            }
            else
            {
                this.ProcTimeoutSeconds = procTimeoutSeconds;
            }
            
            // to ensure "maxNumOfGenerations" is required (not null)
            if (maxNumOfGenerations == null)
            {
                throw new InvalidDataException("maxNumOfGenerations is a required property for OptimizationEngineConfig and cannot be null");
            }
            else
            {
                this.MaxNumOfGenerations = maxNumOfGenerations;
            }
            
            this.HyperVolume = hyperVolume;
            // use default value if no "crossoverDistributionIndex" provided
            if (crossoverDistributionIndex == null)
            {
                this.CrossoverDistributionIndex = 20;
            }
            else
            {
                this.CrossoverDistributionIndex = crossoverDistributionIndex;
            }
            // use default value if no "crossoverProbability" provided
            if (crossoverProbability == null)
            {
                this.CrossoverProbability = 0.9D;
            }
            else
            {
                this.CrossoverProbability = crossoverProbability;
            }
            // use default value if no "mutationDistributionIndex" provided
            if (mutationDistributionIndex == null)
            {
                this.MutationDistributionIndex = 20;
            }
            else
            {
                this.MutationDistributionIndex = mutationDistributionIndex;
            }
            this.MutationProbability = mutationProbability;
            // use default value if no "populationSize" provided
            if (populationSize == null)
            {
                this.PopulationSize = 50;
            }
            else
            {
                this.PopulationSize = populationSize;
            }
            this.HyperVolume = hyperVolume;
        }
        
        /// <summary>
        /// Gets or Sets CrossoverDistributionIndex
        /// </summary>
        [DataMember(Name="crossoverDistributionIndex", EmitDefaultValue=false)]
        public int CrossoverDistributionIndex { get; set; }

        /// <summary>
        /// Gets or Sets CrossoverProbability
        /// </summary>
        [DataMember(Name="crossoverProbability", EmitDefaultValue=false)]
        public double CrossoverProbability { get; set; }

        /// <summary>
        /// Gets or Sets MutationDistributionIndex
        /// </summary>
        [DataMember(Name="mutationDistributionIndex", EmitDefaultValue=false)]
        public int MutationDistributionIndex { get; set; }

        /// <summary>
        /// Gets or Sets MutationProbability
        /// </summary>
        [DataMember(Name="mutationProbability", EmitDefaultValue=false)]
        public double MutationProbability { get; set; }

        /// <summary>
        /// Time in seconds in which individual network must finish training.  If not finished in time error will have maximum value.
        /// </summary>
        /// <value>Time in seconds in which individual network must finish training.  If not finished in time error will have maximum value.</value>
        [DataMember(Name="procTimeoutSeconds", EmitDefaultValue=true)]
        public int ProcTimeoutSeconds { get; set; }

        /// <summary>
        /// Maximum number of generations in which to find optimal network
        /// </summary>
        /// <value>Maximum number of generations in which to find optimal network</value>
        [DataMember(Name="maxNumOfGenerations", EmitDefaultValue=true)]
        public int MaxNumOfGenerations { get; set; }

        /// <summary>
        /// Number of individials in one generation
        /// </summary>
        /// <value>Number of individials in one generation</value>
        [DataMember(Name="populationSize", EmitDefaultValue=false)]
        public int PopulationSize { get; set; }

        /// <summary>
        /// Define hyper volume for early stopping
        /// </summary>
        /// <value>Define hyper volume for early stopping</value>
        [DataMember(Name="hyperVolume", EmitDefaultValue=true)]
        public ConvergencyCriterion HyperVolume { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OptimizationEngineConfig {\n");
            sb.Append("  CrossoverDistributionIndex: ").Append(CrossoverDistributionIndex).Append("\n");
            sb.Append("  CrossoverProbability: ").Append(CrossoverProbability).Append("\n");
            sb.Append("  MutationDistributionIndex: ").Append(MutationDistributionIndex).Append("\n");
            sb.Append("  MutationProbability: ").Append(MutationProbability).Append("\n");
            sb.Append("  ProcTimeoutSeconds: ").Append(ProcTimeoutSeconds).Append("\n");
            sb.Append("  MaxNumOfGenerations: ").Append(MaxNumOfGenerations).Append("\n");
            sb.Append("  PopulationSize: ").Append(PopulationSize).Append("\n");
            sb.Append("  HyperVolume: ").Append(HyperVolume).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OptimizationEngineConfig);
        }

        /// <summary>
        /// Returns true if OptimizationEngineConfig instances are equal
        /// </summary>
        /// <param name="input">Instance of OptimizationEngineConfig to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OptimizationEngineConfig input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CrossoverDistributionIndex == input.CrossoverDistributionIndex ||
                    (this.CrossoverDistributionIndex != null &&
                    this.CrossoverDistributionIndex.Equals(input.CrossoverDistributionIndex))
                ) && 
                (
                    this.CrossoverProbability == input.CrossoverProbability ||
                    (this.CrossoverProbability != null &&
                    this.CrossoverProbability.Equals(input.CrossoverProbability))
                ) && 
                (
                    this.MutationDistributionIndex == input.MutationDistributionIndex ||
                    (this.MutationDistributionIndex != null &&
                    this.MutationDistributionIndex.Equals(input.MutationDistributionIndex))
                ) && 
                (
                    this.MutationProbability == input.MutationProbability ||
                    (this.MutationProbability != null &&
                    this.MutationProbability.Equals(input.MutationProbability))
                ) && 
                (
                    this.ProcTimeoutSeconds == input.ProcTimeoutSeconds ||
                    (this.ProcTimeoutSeconds != null &&
                    this.ProcTimeoutSeconds.Equals(input.ProcTimeoutSeconds))
                ) && 
                (
                    this.MaxNumOfGenerations == input.MaxNumOfGenerations ||
                    (this.MaxNumOfGenerations != null &&
                    this.MaxNumOfGenerations.Equals(input.MaxNumOfGenerations))
                ) && 
                (
                    this.PopulationSize == input.PopulationSize ||
                    (this.PopulationSize != null &&
                    this.PopulationSize.Equals(input.PopulationSize))
                ) && 
                (
                    this.HyperVolume == input.HyperVolume ||
                    (this.HyperVolume != null &&
                    this.HyperVolume.Equals(input.HyperVolume))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CrossoverDistributionIndex != null)
                    hashCode = hashCode * 59 + this.CrossoverDistributionIndex.GetHashCode();
                if (this.CrossoverProbability != null)
                    hashCode = hashCode * 59 + this.CrossoverProbability.GetHashCode();
                if (this.MutationDistributionIndex != null)
                    hashCode = hashCode * 59 + this.MutationDistributionIndex.GetHashCode();
                if (this.MutationProbability != null)
                    hashCode = hashCode * 59 + this.MutationProbability.GetHashCode();
                if (this.ProcTimeoutSeconds != null)
                    hashCode = hashCode * 59 + this.ProcTimeoutSeconds.GetHashCode();
                if (this.MaxNumOfGenerations != null)
                    hashCode = hashCode * 59 + this.MaxNumOfGenerations.GetHashCode();
                if (this.PopulationSize != null)
                    hashCode = hashCode * 59 + this.PopulationSize.GetHashCode();
                if (this.HyperVolume != null)
                    hashCode = hashCode * 59 + this.HyperVolume.GetHashCode();
                return hashCode;
            }
        }
    }

}
