/* 
 * BlackFox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = BlackFoxCSharp.Client.SwaggerDateConverter;

namespace BlackFoxCSharp.Model
{
    /// <summary>
    /// OptimizationEngineConfig
    /// </summary>
    [DataContract]
    public partial class OptimizationEngineConfig :  IEquatable<OptimizationEngineConfig>
    {
        /// <summary>
        /// Defines OptimizationAlgorithm
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OptimizationAlgorithmEnum
        {
            
            /// <summary>
            /// Enum SimpleGA for value: SimpleGA
            /// </summary>
            [EnumMember(Value = "SimpleGA")]
            SimpleGA = 1,
            
            /// <summary>
            /// Enum VidnerovaNeruda for value: VidnerovaNeruda
            /// </summary>
            [EnumMember(Value = "VidnerovaNeruda")]
            VidnerovaNeruda = 2
        }

        /// <summary>
        /// Gets or Sets OptimizationAlgorithm
        /// </summary>
        [DataMember(Name="optimizationAlgorithm", EmitDefaultValue=false)]
        public OptimizationAlgorithmEnum? OptimizationAlgorithm { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OptimizationEngineConfig" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OptimizationEngineConfig() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OptimizationEngineConfig" /> class.
        /// </summary>
        /// <param name="optimizationAlgorithm">optimizationAlgorithm.</param>
        /// <param name="crossoverDistributionIndex">crossoverDistributionIndex.</param>
        /// <param name="crossoverProbability">crossoverProbability.</param>
        /// <param name="mutationDistributionIndex">mutationDistributionIndex.</param>
        /// <param name="mutationProbability">mutationProbability.</param>
        /// <param name="procTimeoutMiliseconds">procTimeoutMiliseconds (required).</param>
        /// <param name="maxNumOfGenerations">maxNumOfGenerations.</param>
        /// <param name="populationSize">populationSize.</param>
        /// <param name="hyperVolume">hyperVolume.</param>
        public OptimizationEngineConfig(OptimizationAlgorithmEnum? optimizationAlgorithm = default(OptimizationAlgorithmEnum?), int? crossoverDistributionIndex = default(int?), double? crossoverProbability = default(double?), int? mutationDistributionIndex = default(int?), double? mutationProbability = default(double?), int? procTimeoutMiliseconds = default(int?), int? maxNumOfGenerations = default(int?), int? populationSize = default(int?), ConvergencyCriterion hyperVolume = default(ConvergencyCriterion))
        {
            // to ensure "procTimeoutMiliseconds" is required (not null)
            if (procTimeoutMiliseconds == null)
            {
                throw new InvalidDataException("procTimeoutMiliseconds is a required property for OptimizationEngineConfig and cannot be null");
            }
            else
            {
                this.ProcTimeoutMiliseconds = procTimeoutMiliseconds;
            }
            this.OptimizationAlgorithm = optimizationAlgorithm;
            this.CrossoverDistributionIndex = crossoverDistributionIndex;
            this.CrossoverProbability = crossoverProbability;
            this.MutationDistributionIndex = mutationDistributionIndex;
            this.MutationProbability = mutationProbability;
            this.MaxNumOfGenerations = maxNumOfGenerations;
            this.PopulationSize = populationSize;
            this.HyperVolume = hyperVolume;
        }
        

        /// <summary>
        /// Gets or Sets CrossoverDistributionIndex
        /// </summary>
        [DataMember(Name="crossoverDistributionIndex", EmitDefaultValue=false)]
        public int? CrossoverDistributionIndex { get; set; }

        /// <summary>
        /// Gets or Sets CrossoverProbability
        /// </summary>
        [DataMember(Name="crossoverProbability", EmitDefaultValue=false)]
        public double? CrossoverProbability { get; set; }

        /// <summary>
        /// Gets or Sets MutationDistributionIndex
        /// </summary>
        [DataMember(Name="mutationDistributionIndex", EmitDefaultValue=false)]
        public int? MutationDistributionIndex { get; set; }

        /// <summary>
        /// Gets or Sets MutationProbability
        /// </summary>
        [DataMember(Name="mutationProbability", EmitDefaultValue=false)]
        public double? MutationProbability { get; set; }

        /// <summary>
        /// Gets or Sets ProcTimeoutMiliseconds
        /// </summary>
        [DataMember(Name="procTimeoutMiliseconds", EmitDefaultValue=false)]
        public int? ProcTimeoutMiliseconds { get; set; }

        /// <summary>
        /// Gets or Sets MaxNumOfGenerations
        /// </summary>
        [DataMember(Name="maxNumOfGenerations", EmitDefaultValue=false)]
        public int? MaxNumOfGenerations { get; set; }

        /// <summary>
        /// Gets or Sets PopulationSize
        /// </summary>
        [DataMember(Name="populationSize", EmitDefaultValue=false)]
        public int? PopulationSize { get; set; }

        /// <summary>
        /// Gets or Sets HyperVolume
        /// </summary>
        [DataMember(Name="hyperVolume", EmitDefaultValue=false)]
        public ConvergencyCriterion HyperVolume { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OptimizationEngineConfig {\n");
            sb.Append("  OptimizationAlgorithm: ").Append(OptimizationAlgorithm).Append("\n");
            sb.Append("  CrossoverDistributionIndex: ").Append(CrossoverDistributionIndex).Append("\n");
            sb.Append("  CrossoverProbability: ").Append(CrossoverProbability).Append("\n");
            sb.Append("  MutationDistributionIndex: ").Append(MutationDistributionIndex).Append("\n");
            sb.Append("  MutationProbability: ").Append(MutationProbability).Append("\n");
            sb.Append("  ProcTimeoutMiliseconds: ").Append(ProcTimeoutMiliseconds).Append("\n");
            sb.Append("  MaxNumOfGenerations: ").Append(MaxNumOfGenerations).Append("\n");
            sb.Append("  PopulationSize: ").Append(PopulationSize).Append("\n");
            sb.Append("  HyperVolume: ").Append(HyperVolume).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OptimizationEngineConfig);
        }

        /// <summary>
        /// Returns true if OptimizationEngineConfig instances are equal
        /// </summary>
        /// <param name="input">Instance of OptimizationEngineConfig to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OptimizationEngineConfig input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OptimizationAlgorithm == input.OptimizationAlgorithm ||
                    (this.OptimizationAlgorithm != null &&
                    this.OptimizationAlgorithm.Equals(input.OptimizationAlgorithm))
                ) && 
                (
                    this.CrossoverDistributionIndex == input.CrossoverDistributionIndex ||
                    (this.CrossoverDistributionIndex != null &&
                    this.CrossoverDistributionIndex.Equals(input.CrossoverDistributionIndex))
                ) && 
                (
                    this.CrossoverProbability == input.CrossoverProbability ||
                    (this.CrossoverProbability != null &&
                    this.CrossoverProbability.Equals(input.CrossoverProbability))
                ) && 
                (
                    this.MutationDistributionIndex == input.MutationDistributionIndex ||
                    (this.MutationDistributionIndex != null &&
                    this.MutationDistributionIndex.Equals(input.MutationDistributionIndex))
                ) && 
                (
                    this.MutationProbability == input.MutationProbability ||
                    (this.MutationProbability != null &&
                    this.MutationProbability.Equals(input.MutationProbability))
                ) && 
                (
                    this.ProcTimeoutMiliseconds == input.ProcTimeoutMiliseconds ||
                    (this.ProcTimeoutMiliseconds != null &&
                    this.ProcTimeoutMiliseconds.Equals(input.ProcTimeoutMiliseconds))
                ) && 
                (
                    this.MaxNumOfGenerations == input.MaxNumOfGenerations ||
                    (this.MaxNumOfGenerations != null &&
                    this.MaxNumOfGenerations.Equals(input.MaxNumOfGenerations))
                ) && 
                (
                    this.PopulationSize == input.PopulationSize ||
                    (this.PopulationSize != null &&
                    this.PopulationSize.Equals(input.PopulationSize))
                ) && 
                (
                    this.HyperVolume == input.HyperVolume ||
                    (this.HyperVolume != null &&
                    this.HyperVolume.Equals(input.HyperVolume))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OptimizationAlgorithm != null)
                    hashCode = hashCode * 59 + this.OptimizationAlgorithm.GetHashCode();
                if (this.CrossoverDistributionIndex != null)
                    hashCode = hashCode * 59 + this.CrossoverDistributionIndex.GetHashCode();
                if (this.CrossoverProbability != null)
                    hashCode = hashCode * 59 + this.CrossoverProbability.GetHashCode();
                if (this.MutationDistributionIndex != null)
                    hashCode = hashCode * 59 + this.MutationDistributionIndex.GetHashCode();
                if (this.MutationProbability != null)
                    hashCode = hashCode * 59 + this.MutationProbability.GetHashCode();
                if (this.ProcTimeoutMiliseconds != null)
                    hashCode = hashCode * 59 + this.ProcTimeoutMiliseconds.GetHashCode();
                if (this.MaxNumOfGenerations != null)
                    hashCode = hashCode * 59 + this.MaxNumOfGenerations.GetHashCode();
                if (this.PopulationSize != null)
                    hashCode = hashCode * 59 + this.PopulationSize.GetHashCode();
                if (this.HyperVolume != null)
                    hashCode = hashCode * 59 + this.HyperVolume.GetHashCode();
                return hashCode;
            }
        }
    }

}
