/* 
 * BlackFox
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = BlackFoxCSharp.Client.OpenAPIDateConverter;

namespace BlackFoxCSharp.Model
{
    /// <summary>
    /// Defines ProblemType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ProblemType
    {
        /// <summary>
        /// Enum Regression for value: Regression
        /// </summary>
        [EnumMember(Value = "Regression")]
        Regression = 1,

        /// <summary>
        /// Enum BinaryClassification for value: BinaryClassification
        /// </summary>
        [EnumMember(Value = "BinaryClassification")]
        BinaryClassification = 2,

        /// <summary>
        /// Enum MultiClassClassification for value: MultiClassClassification
        /// </summary>
        [EnumMember(Value = "MultiClassClassification")]
        MultiClassClassification = 3

    }

}
