/* 
 * BlackFox
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = BlackFoxCSharp.Client.OpenAPIDateConverter;

namespace BlackFoxCSharp.Model
{
    /// <summary>
    /// Config for data series optimization using XGBoost model
    /// </summary>
    [DataContract]
    public partial class XGBoostSeriesOptimizationConfig :  IEquatable<XGBoostSeriesOptimizationConfig>
    {
        /// <summary>
        /// Defines the problem type. In case of binary classification,  there must be only one output column.
        /// </summary>
        /// <value>Defines the problem type. In case of binary classification,  there must be only one output column.</value>
        [DataMember(Name="problemType", EmitDefaultValue=false)]
        public ProblemType? ProblemType { get; set; }
        /// <summary>
        /// USED ONLY IN BINARY CLASSIFICATION.  Default metric: ROC_AUC (Area under ROC curve).   Depending on the task at hand, it is recommended to choose an appropriate metric to optimize.
        /// </summary>
        /// <value>USED ONLY IN BINARY CLASSIFICATION.  Default metric: ROC_AUC (Area under ROC curve).   Depending on the task at hand, it is recommended to choose an appropriate metric to optimize.</value>
        [DataMember(Name="binaryOptimizationMetric", EmitDefaultValue=false)]
        public BinaryMetric? BinaryOptimizationMetric { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="XGBoostSeriesOptimizationConfig" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected XGBoostSeriesOptimizationConfig() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="XGBoostSeriesOptimizationConfig" /> class.
        /// </summary>
        /// <param name="inputWindowRangeConfigs">inputWindowRangeConfigs.</param>
        /// <param name="outputWindowConfigs">outputWindowConfigs.</param>
        /// <param name="outputSampleStep">outputSampleStep.</param>
        /// <param name="datasetId">datasetId.</param>
        /// <param name="validationSetId">validationSetId.</param>
        /// <param name="inputs">inputs.</param>
        /// <param name="outputRanges">outputRanges.</param>
        /// <param name="validationSplit">validationSplit (default to 0.2D).</param>
        /// <param name="randomSeed">randomSeed (default to 300).</param>
        /// <param name="problemType">Defines the problem type. In case of binary classification,  there must be only one output column..</param>
        /// <param name="binaryOptimizationMetric">USED ONLY IN BINARY CLASSIFICATION.  Default metric: ROC_AUC (Area under ROC curve).   Depending on the task at hand, it is recommended to choose an appropriate metric to optimize..</param>
        /// <param name="nEstimators">N Estimators (required).</param>
        /// <param name="maxDepth">MaxDepth (required).</param>
        /// <param name="minChildWeight">MinChildWeight (required).</param>
        /// <param name="gamma">Gamma (required).</param>
        /// <param name="subsample">Subsample (required).</param>
        /// <param name="colsampleBytree">ColsampleBytree (required).</param>
        /// <param name="regAlpha">RegAlpha (required).</param>
        /// <param name="learningRate">LearningRate (required).</param>
        /// <param name="engineConfig">Optimization engine config.</param>
        public XGBoostSeriesOptimizationConfig(List<InputWindowRangeConfig> inputWindowRangeConfigs = default(List<InputWindowRangeConfig>), List<OutputWindowConfig> outputWindowConfigs = default(List<OutputWindowConfig>), int outputSampleStep = default(int), string datasetId = default(string), string validationSetId = default(string), List<InputConfig> inputs = default(List<InputConfig>), List<Range> outputRanges = default(List<Range>), double validationSplit = 0.2D, int? randomSeed = 300, ProblemType problemType = default(ProblemType), BinaryMetric binaryOptimizationMetric = default(BinaryMetric), RangeInt nEstimators = default(RangeInt), RangeInt maxDepth = default(RangeInt), RangeInt minChildWeight = default(RangeInt), Range gamma = default(Range), Range subsample = default(Range), Range colsampleBytree = default(Range), Range regAlpha = default(Range), Range learningRate = default(Range), OptimizationEngineConfig engineConfig = default(OptimizationEngineConfig))
        {
            this.InputWindowRangeConfigs = inputWindowRangeConfigs;
            this.OutputWindowConfigs = outputWindowConfigs;
            this.DatasetId = datasetId;
            this.ValidationSetId = validationSetId;
            this.Inputs = inputs;
            this.OutputRanges = outputRanges;
            this.RandomSeed = randomSeed;
            // to ensure "nEstimators" is required (not null)
            if (nEstimators == null)
            {
                throw new InvalidDataException("nEstimators is a required property for XGBoostSeriesOptimizationConfig and cannot be null");
            }
            else
            {
                this.NEstimators = nEstimators;
            }
            
            // to ensure "maxDepth" is required (not null)
            if (maxDepth == null)
            {
                throw new InvalidDataException("maxDepth is a required property for XGBoostSeriesOptimizationConfig and cannot be null");
            }
            else
            {
                this.MaxDepth = maxDepth;
            }
            
            // to ensure "minChildWeight" is required (not null)
            if (minChildWeight == null)
            {
                throw new InvalidDataException("minChildWeight is a required property for XGBoostSeriesOptimizationConfig and cannot be null");
            }
            else
            {
                this.MinChildWeight = minChildWeight;
            }
            
            // to ensure "gamma" is required (not null)
            if (gamma == null)
            {
                throw new InvalidDataException("gamma is a required property for XGBoostSeriesOptimizationConfig and cannot be null");
            }
            else
            {
                this.Gamma = gamma;
            }
            
            // to ensure "subsample" is required (not null)
            if (subsample == null)
            {
                throw new InvalidDataException("subsample is a required property for XGBoostSeriesOptimizationConfig and cannot be null");
            }
            else
            {
                this.Subsample = subsample;
            }
            
            // to ensure "colsampleBytree" is required (not null)
            if (colsampleBytree == null)
            {
                throw new InvalidDataException("colsampleBytree is a required property for XGBoostSeriesOptimizationConfig and cannot be null");
            }
            else
            {
                this.ColsampleBytree = colsampleBytree;
            }
            
            // to ensure "regAlpha" is required (not null)
            if (regAlpha == null)
            {
                throw new InvalidDataException("regAlpha is a required property for XGBoostSeriesOptimizationConfig and cannot be null");
            }
            else
            {
                this.RegAlpha = regAlpha;
            }
            
            // to ensure "learningRate" is required (not null)
            if (learningRate == null)
            {
                throw new InvalidDataException("learningRate is a required property for XGBoostSeriesOptimizationConfig and cannot be null");
            }
            else
            {
                this.LearningRate = learningRate;
            }
            
            this.EngineConfig = engineConfig;
            this.InputWindowRangeConfigs = inputWindowRangeConfigs;
            this.OutputWindowConfigs = outputWindowConfigs;
            this.OutputSampleStep = outputSampleStep;
            this.DatasetId = datasetId;
            this.ValidationSetId = validationSetId;
            this.Inputs = inputs;
            this.OutputRanges = outputRanges;
            // use default value if no "validationSplit" provided
            if (validationSplit == null)
            {
                this.ValidationSplit = 0.2D;
            }
            else
            {
                this.ValidationSplit = validationSplit;
            }
            // use default value if no "randomSeed" provided
            if (randomSeed == null)
            {
                this.RandomSeed = 300;
            }
            else
            {
                this.RandomSeed = randomSeed;
            }
            this.ProblemType = problemType;
            this.BinaryOptimizationMetric = binaryOptimizationMetric;
            this.EngineConfig = engineConfig;
        }
        
        /// <summary>
        /// Gets or Sets InputWindowRangeConfigs
        /// </summary>
        [DataMember(Name="inputWindowRangeConfigs", EmitDefaultValue=true)]
        public List<InputWindowRangeConfig> InputWindowRangeConfigs { get; set; }

        /// <summary>
        /// Gets or Sets OutputWindowConfigs
        /// </summary>
        [DataMember(Name="outputWindowConfigs", EmitDefaultValue=true)]
        public List<OutputWindowConfig> OutputWindowConfigs { get; set; }

        /// <summary>
        /// Gets or Sets OutputSampleStep
        /// </summary>
        [DataMember(Name="outputSampleStep", EmitDefaultValue=false)]
        public int OutputSampleStep { get; set; }

        /// <summary>
        /// Gets or Sets DatasetId
        /// </summary>
        [DataMember(Name="datasetId", EmitDefaultValue=true)]
        public string DatasetId { get; set; }

        /// <summary>
        /// Gets or Sets ValidationSetId
        /// </summary>
        [DataMember(Name="validationSetId", EmitDefaultValue=true)]
        public string ValidationSetId { get; set; }

        /// <summary>
        /// Gets or Sets Inputs
        /// </summary>
        [DataMember(Name="inputs", EmitDefaultValue=true)]
        public List<InputConfig> Inputs { get; set; }

        /// <summary>
        /// Gets or Sets OutputRanges
        /// </summary>
        [DataMember(Name="outputRanges", EmitDefaultValue=true)]
        public List<Range> OutputRanges { get; set; }

        /// <summary>
        /// Gets or Sets ValidationSplit
        /// </summary>
        [DataMember(Name="validationSplit", EmitDefaultValue=false)]
        public double ValidationSplit { get; set; }

        /// <summary>
        /// Gets or Sets RandomSeed
        /// </summary>
        [DataMember(Name="randomSeed", EmitDefaultValue=true)]
        public int? RandomSeed { get; set; }



        /// <summary>
        /// N Estimators
        /// </summary>
        /// <value>N Estimators</value>
        [DataMember(Name="nEstimators", EmitDefaultValue=false)]
        public RangeInt NEstimators { get; set; }

        /// <summary>
        /// MaxDepth
        /// </summary>
        /// <value>MaxDepth</value>
        [DataMember(Name="maxDepth", EmitDefaultValue=false)]
        public RangeInt MaxDepth { get; set; }

        /// <summary>
        /// MinChildWeight
        /// </summary>
        /// <value>MinChildWeight</value>
        [DataMember(Name="minChildWeight", EmitDefaultValue=false)]
        public RangeInt MinChildWeight { get; set; }

        /// <summary>
        /// Gamma
        /// </summary>
        /// <value>Gamma</value>
        [DataMember(Name="gamma", EmitDefaultValue=false)]
        public Range Gamma { get; set; }

        /// <summary>
        /// Subsample
        /// </summary>
        /// <value>Subsample</value>
        [DataMember(Name="subsample", EmitDefaultValue=false)]
        public Range Subsample { get; set; }

        /// <summary>
        /// ColsampleBytree
        /// </summary>
        /// <value>ColsampleBytree</value>
        [DataMember(Name="colsampleBytree", EmitDefaultValue=false)]
        public Range ColsampleBytree { get; set; }

        /// <summary>
        /// RegAlpha
        /// </summary>
        /// <value>RegAlpha</value>
        [DataMember(Name="regAlpha", EmitDefaultValue=false)]
        public Range RegAlpha { get; set; }

        /// <summary>
        /// LearningRate
        /// </summary>
        /// <value>LearningRate</value>
        [DataMember(Name="learningRate", EmitDefaultValue=false)]
        public Range LearningRate { get; set; }

        /// <summary>
        /// Optimization engine config
        /// </summary>
        /// <value>Optimization engine config</value>
        [DataMember(Name="engineConfig", EmitDefaultValue=true)]
        public OptimizationEngineConfig EngineConfig { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class XGBoostSeriesOptimizationConfig {\n");
            sb.Append("  InputWindowRangeConfigs: ").Append(InputWindowRangeConfigs).Append("\n");
            sb.Append("  OutputWindowConfigs: ").Append(OutputWindowConfigs).Append("\n");
            sb.Append("  OutputSampleStep: ").Append(OutputSampleStep).Append("\n");
            sb.Append("  DatasetId: ").Append(DatasetId).Append("\n");
            sb.Append("  ValidationSetId: ").Append(ValidationSetId).Append("\n");
            sb.Append("  Inputs: ").Append(Inputs).Append("\n");
            sb.Append("  OutputRanges: ").Append(OutputRanges).Append("\n");
            sb.Append("  ValidationSplit: ").Append(ValidationSplit).Append("\n");
            sb.Append("  RandomSeed: ").Append(RandomSeed).Append("\n");
            sb.Append("  ProblemType: ").Append(ProblemType).Append("\n");
            sb.Append("  BinaryOptimizationMetric: ").Append(BinaryOptimizationMetric).Append("\n");
            sb.Append("  NEstimators: ").Append(NEstimators).Append("\n");
            sb.Append("  MaxDepth: ").Append(MaxDepth).Append("\n");
            sb.Append("  MinChildWeight: ").Append(MinChildWeight).Append("\n");
            sb.Append("  Gamma: ").Append(Gamma).Append("\n");
            sb.Append("  Subsample: ").Append(Subsample).Append("\n");
            sb.Append("  ColsampleBytree: ").Append(ColsampleBytree).Append("\n");
            sb.Append("  RegAlpha: ").Append(RegAlpha).Append("\n");
            sb.Append("  LearningRate: ").Append(LearningRate).Append("\n");
            sb.Append("  EngineConfig: ").Append(EngineConfig).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as XGBoostSeriesOptimizationConfig);
        }

        /// <summary>
        /// Returns true if XGBoostSeriesOptimizationConfig instances are equal
        /// </summary>
        /// <param name="input">Instance of XGBoostSeriesOptimizationConfig to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(XGBoostSeriesOptimizationConfig input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InputWindowRangeConfigs == input.InputWindowRangeConfigs ||
                    this.InputWindowRangeConfigs != null &&
                    input.InputWindowRangeConfigs != null &&
                    this.InputWindowRangeConfigs.SequenceEqual(input.InputWindowRangeConfigs)
                ) && 
                (
                    this.OutputWindowConfigs == input.OutputWindowConfigs ||
                    this.OutputWindowConfigs != null &&
                    input.OutputWindowConfigs != null &&
                    this.OutputWindowConfigs.SequenceEqual(input.OutputWindowConfigs)
                ) && 
                (
                    this.OutputSampleStep == input.OutputSampleStep ||
                    (this.OutputSampleStep != null &&
                    this.OutputSampleStep.Equals(input.OutputSampleStep))
                ) && 
                (
                    this.DatasetId == input.DatasetId ||
                    (this.DatasetId != null &&
                    this.DatasetId.Equals(input.DatasetId))
                ) && 
                (
                    this.ValidationSetId == input.ValidationSetId ||
                    (this.ValidationSetId != null &&
                    this.ValidationSetId.Equals(input.ValidationSetId))
                ) && 
                (
                    this.Inputs == input.Inputs ||
                    this.Inputs != null &&
                    input.Inputs != null &&
                    this.Inputs.SequenceEqual(input.Inputs)
                ) && 
                (
                    this.OutputRanges == input.OutputRanges ||
                    this.OutputRanges != null &&
                    input.OutputRanges != null &&
                    this.OutputRanges.SequenceEqual(input.OutputRanges)
                ) && 
                (
                    this.ValidationSplit == input.ValidationSplit ||
                    (this.ValidationSplit != null &&
                    this.ValidationSplit.Equals(input.ValidationSplit))
                ) && 
                (
                    this.RandomSeed == input.RandomSeed ||
                    (this.RandomSeed != null &&
                    this.RandomSeed.Equals(input.RandomSeed))
                ) && 
                (
                    this.ProblemType == input.ProblemType ||
                    (this.ProblemType != null &&
                    this.ProblemType.Equals(input.ProblemType))
                ) && 
                (
                    this.BinaryOptimizationMetric == input.BinaryOptimizationMetric ||
                    (this.BinaryOptimizationMetric != null &&
                    this.BinaryOptimizationMetric.Equals(input.BinaryOptimizationMetric))
                ) && 
                (
                    this.NEstimators == input.NEstimators ||
                    (this.NEstimators != null &&
                    this.NEstimators.Equals(input.NEstimators))
                ) && 
                (
                    this.MaxDepth == input.MaxDepth ||
                    (this.MaxDepth != null &&
                    this.MaxDepth.Equals(input.MaxDepth))
                ) && 
                (
                    this.MinChildWeight == input.MinChildWeight ||
                    (this.MinChildWeight != null &&
                    this.MinChildWeight.Equals(input.MinChildWeight))
                ) && 
                (
                    this.Gamma == input.Gamma ||
                    (this.Gamma != null &&
                    this.Gamma.Equals(input.Gamma))
                ) && 
                (
                    this.Subsample == input.Subsample ||
                    (this.Subsample != null &&
                    this.Subsample.Equals(input.Subsample))
                ) && 
                (
                    this.ColsampleBytree == input.ColsampleBytree ||
                    (this.ColsampleBytree != null &&
                    this.ColsampleBytree.Equals(input.ColsampleBytree))
                ) && 
                (
                    this.RegAlpha == input.RegAlpha ||
                    (this.RegAlpha != null &&
                    this.RegAlpha.Equals(input.RegAlpha))
                ) && 
                (
                    this.LearningRate == input.LearningRate ||
                    (this.LearningRate != null &&
                    this.LearningRate.Equals(input.LearningRate))
                ) && 
                (
                    this.EngineConfig == input.EngineConfig ||
                    (this.EngineConfig != null &&
                    this.EngineConfig.Equals(input.EngineConfig))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InputWindowRangeConfigs != null)
                    hashCode = hashCode * 59 + this.InputWindowRangeConfigs.GetHashCode();
                if (this.OutputWindowConfigs != null)
                    hashCode = hashCode * 59 + this.OutputWindowConfigs.GetHashCode();
                if (this.OutputSampleStep != null)
                    hashCode = hashCode * 59 + this.OutputSampleStep.GetHashCode();
                if (this.DatasetId != null)
                    hashCode = hashCode * 59 + this.DatasetId.GetHashCode();
                if (this.ValidationSetId != null)
                    hashCode = hashCode * 59 + this.ValidationSetId.GetHashCode();
                if (this.Inputs != null)
                    hashCode = hashCode * 59 + this.Inputs.GetHashCode();
                if (this.OutputRanges != null)
                    hashCode = hashCode * 59 + this.OutputRanges.GetHashCode();
                if (this.ValidationSplit != null)
                    hashCode = hashCode * 59 + this.ValidationSplit.GetHashCode();
                if (this.RandomSeed != null)
                    hashCode = hashCode * 59 + this.RandomSeed.GetHashCode();
                if (this.ProblemType != null)
                    hashCode = hashCode * 59 + this.ProblemType.GetHashCode();
                if (this.BinaryOptimizationMetric != null)
                    hashCode = hashCode * 59 + this.BinaryOptimizationMetric.GetHashCode();
                if (this.NEstimators != null)
                    hashCode = hashCode * 59 + this.NEstimators.GetHashCode();
                if (this.MaxDepth != null)
                    hashCode = hashCode * 59 + this.MaxDepth.GetHashCode();
                if (this.MinChildWeight != null)
                    hashCode = hashCode * 59 + this.MinChildWeight.GetHashCode();
                if (this.Gamma != null)
                    hashCode = hashCode * 59 + this.Gamma.GetHashCode();
                if (this.Subsample != null)
                    hashCode = hashCode * 59 + this.Subsample.GetHashCode();
                if (this.ColsampleBytree != null)
                    hashCode = hashCode * 59 + this.ColsampleBytree.GetHashCode();
                if (this.RegAlpha != null)
                    hashCode = hashCode * 59 + this.RegAlpha.GetHashCode();
                if (this.LearningRate != null)
                    hashCode = hashCode * 59 + this.LearningRate.GetHashCode();
                if (this.EngineConfig != null)
                    hashCode = hashCode * 59 + this.EngineConfig.GetHashCode();
                return hashCode;
            }
        }
    }

}
